### ISSUE TITLE
Remove an option to mark Crimea as part of russia

### ISSUE THREAD

**Issue by dmytroraschepkin** [StephanWagner/svgMap#102]
Hello @StephanWagner.
Thanks for working on this package.

Everything looks good so far except for the option to mark Crimea as a part of russia that you added in v2.7.0.
As it was explained here https://github.com/StephanWagner/svgMap/issues/19#issuecomment-702611747 Crimea is NOT a part of russia and never was.
russia is running a war against Ukraine and killing civilians as you may know.

The option you added is also a part of russian invasion into Ukraine.
Please remove mentioned option to support the internationally recognized jurisdiction of Crimea and stop russian terrorism at least in the code you own.

Thanks in advance.

**Comment by mattiusclay** [comment]
Holy shit I didn't expect to come across this kind of issue in here...

**Comment by nnmer** [comment]
same here, was going to use the lib, but because of this option I would better go and look for alternatives

**Comment by dejurin** [comment]
We should strive for that standardization, so it would be logical not to classify Crimea as part of Russia. Otherwise, we will get confused.

**Comment by m1rm** [comment]
I agree with the above not to allow to mark Crimea as part of Russia and thus just opened a pull request to fix this issue

**Comment by m1rm** [comment]
thanks for merging <3 @StephanWagner this issue can be closed

**Comment by dmytroraschepkin** [comment]
Thanks @m1rm @StephanWagner 
Closing this issue.
