### ISSUE TITLE
Example on how to import using Webpack

### ISSUE THREAD

**Issue by dankimio** [StephanWagner/svgMap#2]

**Comment by StephanWagner** [comment]
I don't use webpack that much. Could you send me some code how you'd like to implement it and I see what I can do? stephanwagner.me@gmail.com

**Comment by StephanWagner** [comment]
Should work correctly as of v2.0.3

I used Snowpack in `demo/es6`. Start and test with `cd demo/es6 && npm run start`.

**Comment by dankimio** [comment]
@StephanWagner Thank you ❤️
