### ISSUE TITLE
disable mousover if no data

### ISSUE THREAD

**Issue by ma-gu-16** [StephanWagner/svgMap#20]
Hi, is it possible to disable the mousover if there is no data ?

**Comment by StephanWagner** [comment]
Not at the moment. Flagging this issue with enhancement, might be a nice option.

**Comment by ma-gu-16** [comment]
anyways severall callbacks would be nice. before, after like the pantozoom script you use ;-) 
if i need it later in my project, i share it.

**Comment by intermundos** [comment]
+1 here. need to show popup only for country with data.

**Comment by nickbluestone98** [comment]
@intermundos @ma-gu-16 @StephanWagner 

Not the best solution in the world but it works.

You can run the onGetTooltip function comparing the values each time and display: block or display: none.

```
  onGetTooltip(_tooltipDiv, _countryID, countryValues) {
      if (countryValues === undefined) {
        _tooltipDiv.style.display = 'none';
      } else {
        _tooltipDiv.style.display = 'block';
      }
   },
```
