### ISSUE TITLE
Add link to country

### ISSUE THREAD

**Issue by StephanWagner** [StephanWagner/svgMap#22]
Add a link to a page when clicking on a country (or in the tooltip).

**Comment by ahmadbadpey** [comment]
No Idea?

**Comment by StephanWagner** [comment]
I haven't gotten around to implement that yet... It's been quite busy recently.

**Comment by Sena** [comment]
@StephanWagner I made a suggestion, we can improve later, bug this is an solution from now.

**Comment by StephanWagner** [comment]
Thanks @Sena, it's merged.

Only thing I added is that now the pointer is the default pointer when no link is provided.
