### ISSUE TITLE
tooltipContentTable is not defined

### ISSUE THREAD

**Issue by developerkarthee** [StephanWagner/svgMap#25]
![image](https://user-images.githubusercontent.com/20332818/94679520-df596c00-033d-11eb-979f-e3f92cac17fa.png)
I have encountered an exception while mouse hover on the country which had data to view the tooltip, I have added this variable 'tooltipContentTable' in window object to solve this undefined variable exception. could be really helpful if you could declare this variable inside js file.

**Comment by Maximaximum** [comment]
This issue seems to be related to #2 and #3, since it happens while trying to do import like `import svgMap from 'svgmap';`.

It would be great if this library supported the standard es6 module `import svgMap from 'svgmap'` syntax, then I guess that all these issues should be resolved

**Comment by StephanWagner** [comment]
Should now be fixed with v2.0.3
