### ISSUE TITLE
Default Color

### ISSUE THREAD

**Issue by Amm0o** [StephanWagner/svgMap#26]
Hello good afternoon,
I'm creating this ticket to ask you if there is a way to set a default colot for the map

Thank you

**Comment by StephanWagner** [comment]
Do you mean the default gray color?

The colors are appended directly to the SVG path element, so the only way to overwrite the gray color, I could think of, is with following CSS:

```
.svgMap-map-wrapper .svgMap-country[fill="#E2E2E2"] {
    fill: red;
}
```

**Comment by Amm0o** [comment]
Ok thank you for your help
