### ISSUE TITLE
Is it possible to open the associated link in a new tab?

### ISSUE THREAD

**Issue by tavernhell** [StephanWagner/svgMap#40]
I feel like having to go back and forth every time you open a new link can be a downside for some users. 

I tried adding my own JS after setting the options but due to my limited knowledge of the language, I couldn't override the default behaviour.

**Comment by StephanWagner** [comment]
Added option `values.linkTarget` with version 2.2.0.

See here: https://github.com/StephanWagner/svgMap#options
