### ISSUE TITLE
How to fill the countries without data?

### ISSUE THREAD

**Issue by dejurin** [StephanWagner/svgMap#41]
<img width="1033" alt="Снимок экрана 2021-07-17 в 11 53 40" src="https://user-images.githubusercontent.com/4470015/126031836-0811918f-86a2-4bf1-b51e-5953cca51bfe.png">
I'll want filled all countries who use EUR, but color is black only

**Comment by StephanWagner** [comment]
svgMap was never meant to only use one value, so there was a bug that is now fixed in version 2.2.1. 

You still kinda have to "hack" to show the color by setting `colorMin` and `colorMax` to the same color and then set the euro value all to 1.

See this fiddle: https://jsfiddle.net/StephanWagner/z02etcr3/1/

```javascript
new svgMap({
  targetElementID: 'svgMap',
  noDataText: 'Does not use Euro',
  colorMax: '#FF0000',
  colorMin: '#FF0000',
  data: {
    data: {
      euro: {
        name: '',
        format: 'Uses Euro',
        thousandSeparator: ',',
        thresholdMax: 2,
        thresholdMin: 0
      }
    },
    applyData: 'euro',
    values: {
      DE: {euro: 1},
      FR: {euro: 1},
      ES: {euro: 1}
      // ...
    }
  }
});
```

**Comment by StephanWagner** [comment]
Hey @dejurin, i just released v.2.5.2
It should now be much easier to achieve what you are trying to do. I added a demo, feel free to download v2.5.2 and check out the demo file. you can now customize tooltips (#43) and also you can zoom into the euro region if you desire (new option `initialPan`).

<img width="839" alt="Screenshot 2021-07-29 at 23 12 00" src="https://user-images.githubusercontent.com/1636873/127566527-78d398eb-ae5f-4008-b669-2a6e7a31a983.png">

**Comment by dejurin** [comment]
Thank you!

пт, 30 июл. 2021 г. в 00:14, Stephan Wagner ***@***.***>:
