### ISSUE TITLE
Vue Support?

### ISSUE THREAD

**Issue by heychazza** [StephanWagner/svgMap#52]
Hi,

Is there any chance that we can see Vue support?

**Comment by StephanWagner** [comment]
Actually, it should work with Vue, there is a demo in `demo/es6` using imports. I haven't tested it with Vue specifically, but I think it should work.

I have a ton of other work at the moment, so for now I'm not working on svgMap. I do habe a huge update planned for Version 3, it will take some time thought.

**Comment by heychazza** [comment]
Sounds perfect, thank you!
