### ISSUE TITLE
Singapore no longer accessible after hovering over Malaysia

### ISSUE THREAD

**Issue by sneaknz** [StephanWagner/svgMap#7]
We noticed when trying to use the map that, even when zoomed in, Singapore was no longer visible or able to be accessed if you have previously hovered over Malaysia (as it brings that particular path to the front, covering Singapore). We resolved this by editing the SVG path data in `mapPaths.js` to clean up the division between the two.

The path information is below in case it is useful for anyone. After updating the path information we just ran the build process again to generate new versions of the combined .js files.

Singapore:
`M1561.4, 563.4l-0.5-0.3l-0.8-0.1l-0.6,0.1l-0.3,0.6 l0.0,0.6L1561.8,564z`

Malaysia:
`M1543.6,532.7l-4.7-2.8l-0.9,1.1l1.4,2.7l-0.4,4.7l2.1,3.4l1,5.3 l3.4,4.3l0.8,3.2l6.7,5l5.4,4.8 0.8-0.1 0-0.6 0.3-0.6 0.6-0.1 0.8,0.1 0.5,0.3 0.4,0.6 l0.6-0.1 l0.1-2.1 l-2.3-5.6 l-2.1-1.8l-0.5-3.8l-0.6-2.1l0.5-2.9l-0.5-4.3l-2.6-4.3l-3.5-3.8l-1.3-0.6 l-1.7,2.6l-3.7,0.8L1543.6,532.7L1543.6,532.7z M1642.6,543.7l-1.2-3.1l3.8-0.4l0.3-2.4l-4.8-2l-3.8-1.7l-0.4-2.8l-3.1-3.2h-2.3 l-2.5,5l-4.1,4.4l-0.1,3.1l-0.1,4.1l-2.7-0.2l-1.1,2.2l-2.7-3.3l-2.6,4l-3.8,5l-6.7,1.4l-2.4,1.2l-0.9,5.4l-4.4,1.2l-4.1-2.2l1,4.3 l3.9,3.5l3.6-1.2l3.6,0.4l3.2-3.2l2.7-0.6l5.4,1.8l4.5-1.3l2.7-8.9l2-2.2l1.7-7.2h6.4l5,1L1642.6,543.7z`

**Comment by StephanWagner** [comment]
Well spotted! Thanks!
Fixed now with v1.3.3: https://github.com/StephanWagner/svgMap/releases/tag/v1.3.3
