### ISSUE TITLE
Add Internet Explorer Support

### ISSUE THREAD

**Issue by StevenMapes** [StephanWagner/svgMap#9]
The library does not work in IE11 :( To test simply go to the example page https://stephanwagner.me/create-world-map-charts-with-svgmap#svgMapDemoGDP and you will not see any map.

It does work in edge though it has scaling issues

As much as we may all not like internet explorer, IE 11 does supports SVGs, doesn't hit EOL until 2023 and is still used across a lot of corporate netwoks so adding support would be good

The error appears to be around the use of assign at character 29774 of svgmap.min.js

Further investigation shows that it is indeed this line as Object.assign is not supported in IE and needs a polyfill or other work around in order to work

**Comment by StevenMapes** [comment]
I've submitted a PR which updates the readme with an appendix for how to add support using polyfills supplied by https://polyfill.io/v3/url-builder/ which enables IE support without any changes to the this library.

The two required polyfills are Object.assign and  Element.prototype.classList

This is the combined bundle that can be used ```<script src="https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.classList%2CObject.assign"></script>```

**Comment by StephanWagner** [comment]
Can't find a PR.
Reopening as IE11 should be supported.

**Comment by StevenMapes** [comment]
Sorry about that it must have failed to submit. I've sent it now, the PR is just a documentation update

**Comment by StephanWagner** [comment]
Comment added with v1.4.0: https://github.com/StephanWagner/svgMap/releases/tag/v1.4.0
